package api
package handler

import (
	"net/http"
	"os"




















































































}	router.ServeHTTP(w, r)func Handler(w http.ResponseWriter, r *http.Request) {// Handler для Vercel}	}		}			admin.DELETE("/phone-contacts/:id", handlers.DeletePhoneContact)			admin.GET("/phone-contacts", handlers.GetPhoneContacts)			admin.GET("/phone-click-stats", handlers.GetPhoneClickStats)			admin.GET("/visitor-stats", handlers.GetVisitorStats)			// Аналитика						admin.DELETE("/contacts/:id", handlers.DeleteContact)			admin.PUT("/contacts/:id/read", handlers.MarkContactAsRead)			admin.GET("/contacts/:id", handlers.GetContact)			admin.GET("/contacts", handlers.GetContacts)			// Контакты		{		admin.Use(middleware.AuthRequired(), middleware.AdminRequired())		admin := api.Group("/admin")		// Админ маршруты		}			auth.PUT("/profile", handlers.UpdateProfile)			auth.GET("/profile", handlers.GetProfile)		{		auth.Use(middleware.AuthRequired())		auth := api.Group("/")		// Авторизованные маршруты				api.POST("/track-phone-click", handlers.TrackPhoneClick)		api.POST("/track-visitor", handlers.TrackVisitor)		// Аналитика				api.POST("/phone-contact", handlers.CreatePhoneContact)		api.POST("/quick-contact", handlers.CreateQuickContact)		api.POST("/contact", handlers.CreateContact)		// Контактные формы				api.GET("/categories", handlers.GetCategories)		api.GET("/products/:id", handlers.GetProduct)		api.GET("/products", handlers.GetProducts)		api.POST("/login", handlers.Login)		api.POST("/register", handlers.Register)		// Публичные маршруты	{	api := router.Group("/api/v1")	// API маршруты	router.Use(cors.New(config))	config.AllowHeaders = []string{"Origin", "Content-Length", "Content-Type", "Authorization"}	config.AllowMethods = []string{"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}	config.AllowOrigins = []string{"*"}	config := cors.DefaultConfig()	// CORS конфигурация для Vercel		router.Use(gin.Recovery())	router.Use(gin.Logger())	// Middleware		router = gin.New()	// Создание роутера		gin.SetMode(gin.ReleaseMode)	// Настройка Gin в production режиме для Vercel		database.Init()	// Инициализация базы данных		godotenv.Load()	// Загрузка переменных окружения для Vercelfunc init() {var router *gin.Engine)	"github.com/joho/godotenv"	"github.com/gin-contrib/cors"	"github.com/gin-gonic/gin"	"texnousta-backend/internal/middleware"	"texnousta-backend/internal/handlers"	"texnousta-backend/internal/database"